// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/binance-loan/Dashboard.tsx": () => import("../components/mockups/binance-loan/Dashboard.tsx"),
  "./components/mockups/binance-loan/InterestHistory.tsx": () => import("../components/mockups/binance-loan/InterestHistory.tsx"),
  "./components/mockups/binance-loan/LoanDetail.tsx": () => import("../components/mockups/binance-loan/LoanDetail.tsx"),
  "./components/mockups/binance-loan/Login.tsx": () => import("../components/mockups/binance-loan/Login.tsx"),
  "./components/mockups/binance-loan/Onboarding.tsx": () => import("../components/mockups/binance-loan/Onboarding.tsx"),
  "./components/mockups/binance-loan/Settings.tsx": () => import("../components/mockups/binance-loan/Settings.tsx"),
  "./components/mockups/binance-loan/WidgetHomeLarge.tsx": () => import("../components/mockups/binance-loan/WidgetHomeLarge.tsx"),
  "./components/mockups/binance-loan/WidgetHomeMedium.tsx": () => import("../components/mockups/binance-loan/WidgetHomeMedium.tsx"),
  "./components/mockups/binance-loan/WidgetHomeMediumAction.tsx": () => import("../components/mockups/binance-loan/WidgetHomeMediumAction.tsx"),
  "./components/mockups/binance-loan/WidgetHomeMediumLoans.tsx": () => import("../components/mockups/binance-loan/WidgetHomeMediumLoans.tsx"),
  "./components/mockups/binance-loan/WidgetHomeSmall.tsx": () => import("../components/mockups/binance-loan/WidgetHomeSmall.tsx"),
  "./components/mockups/binance-loan/WidgetHomeSmallRisk.tsx": () => import("../components/mockups/binance-loan/WidgetHomeSmallRisk.tsx"),
  "./components/mockups/binance-loan/WidgetLockCircular.tsx": () => import("../components/mockups/binance-loan/WidgetLockCircular.tsx"),
  "./components/mockups/binance-loan/WidgetLockInline.tsx": () => import("../components/mockups/binance-loan/WidgetLockInline.tsx"),
  "./components/mockups/binance-loan/WidgetLockRect.tsx": () => import("../components/mockups/binance-loan/WidgetLockRect.tsx")
};
