/**
 * withSyncedExtensionBuildNumbers
 *
 * Apple requires every embedded binary (widget extension, watch app,
 * watch widget, etc.) to declare the SAME CFBundleVersion as its
 * containing parent app. Otherwise App Store Connect rejects the
 * upload with:
 *
 *   The CFBundleVersion of an app extension ('1') must match that of
 *   its containing parent app ('40').
 *
 * With `appVersionSource: remote` in eas.json, EAS-CLI fetches the
 * next build number from its server on every build and writes it into
 * `config.ios.buildNumber` BEFORE prebuild runs. The main `Ledger`
 * target picks this up automatically because Expo's iOS template uses
 * `$(CURRENT_PROJECT_VERSION)` for CFBundleVersion. But:
 *
 *   1. The hand-written widget `Info.plist` was hardcoded to "1".
 *   2. Targets generated by `@bacons/apple-targets` (LedgerWatch,
 *      LedgerWatchComplication) get their own per-target
 *      CURRENT_PROJECT_VERSION default of "1".
 *
 * So we walk every native target in the generated Xcode project and
 * overwrite CURRENT_PROJECT_VERSION + MARKETING_VERSION on every
 * build configuration with the values resolved from app config. The
 * widget Info.plist is also updated to reference these build settings
 * via `$(CURRENT_PROJECT_VERSION)` / `$(MARKETING_VERSION)` (see the
 * sibling Info.plist edit) so Xcode resolves them at archive time.
 *
 * Plugin order in app.json:
 *   - Must run AFTER `@bacons/apple-targets` so the generated
 *     extension targets exist in the project tree when we walk it.
 *   - Order vs. `withAppleTargetDistributionSigning` doesn't matter —
 *     they touch disjoint build settings.
 */
const { createRequire } = require("node:module");
const path = require("node:path");

const expoPackageJson = require.resolve("expo/package.json", {
  paths: [path.join(__dirname, ".."), process.cwd()],
});
const expoRequire = createRequire(expoPackageJson);
const { withXcodeProject } = expoRequire("@expo/config-plugins");

module.exports = function withSyncedExtensionBuildNumbers(config) {
  return withXcodeProject(config, (cfg) => {
    const proj = cfg.modResults;
    const buildNumber = String(cfg.ios?.buildNumber ?? "1");
    const marketingVersion = String(cfg.version ?? "1.0.0");

    const nativeTargets = proj.pbxNativeTargetSection();
    const configLists = proj.pbxXCConfigurationList();
    const buildConfigs = proj.pbxXCBuildConfigurationSection();

    const targetEntries = Object.entries(nativeTargets).filter(
      ([, value]) => typeof value === "object" && value !== null,
    );

    let patched = 0;
    for (const [, target] of targetEntries) {
      const list = configLists[target.buildConfigurationList];
      if (!list || !Array.isArray(list.buildConfigurations)) continue;
      for (const ref of list.buildConfigurations) {
        const bc = buildConfigs[ref.value];
        if (!bc) continue;
        const settings = (bc.buildSettings ||= {});
        settings.CURRENT_PROJECT_VERSION = buildNumber;
        settings.MARKETING_VERSION = marketingVersion;
        patched += 1;
      }
    }

    console.log(
      `[withSyncedExtensionBuildNumbers] Synced CURRENT_PROJECT_VERSION=${buildNumber}, ` +
        `MARKETING_VERSION=${marketingVersion} across ${patched} build configuration(s).`,
    );
    return cfg;
  });
};
